name: Kanal Listesi Guncelle

on:
  schedule:
    - cron: '*/10 * * * *' # 10 dakikada bir çalışır
  workflow_dispatch: # Manuel başlatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Yazma izni şart

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Kütüphaneleri Yükle
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Kanalları Çek ve Dosyaları Oluştur
        run: python goals.py

      - name: Değişiklikleri Kaydet ve Pushla
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Tüm yeni dosyaları ve klasörleri ekle
          git add playlist.m3u kanallar/
          
          # Değişiklik varsa commit at
          if git diff --staged --quiet; then
            echo "Değişiklik yok."
          else
            git commit -m "Otomatik Güncelleme: $(date)"
            git push
          fi
