name: Kanal Listesini Güncelle

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v3

    - name: Python'u Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Kanalları Çek ve M3U8 Dosyalarını Oluştur
      run: python main.py

    - name: Değişiklikleri Depoya Kaydet
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # Önce tüm değişiklikleri ekle (yeni dosyalar, silinenler, güncellenenler)
        git add -A
        # Değişiklik olup olmadığını kontrol et
        if git diff --staged --quiet; then
          echo "Değişiklik bulunamadı, commit atlanıyor."
        else
          # Sadece değişiklik varsa commit at ve push'la
          git commit -m "Kanal listesi otomatik güncellendi: $(date -u)"
          git push
        fi
